### ISSUE TITLE
Feature Request/Reccomendation: Dex Cornugon Smash?

### ISSUE THREAD

**Issue by TKDancer** [Evilvonbek/DexCarn#1]
first of all, sorry to even make a 'request' out of the blue

but the 'request' is simple as title implies, since you were so kinda to create a Dex version of Dreadful Carnage to work off a piranha strike requirement, would it be possible to either create a dex version of Cornugon Smash that works off Piranha Strike or at least tweaking the existing one to work off either or

**Comment by Evilvonbek** [comment]
Easier and cleaner to create a separate one for purely dex, and nah it's fine as you're probably like me and feel there's a whole lot of dex support missing in game but that's mainly due to it pulling from d&d and it being "STR/CHA/WIS are the only stats that matter unless you want to be a thief" 😆 

Waiting for the TT guru Vek ( the author of TableTop Tweaks and generally who we bounce "is this even close to being TT allowable?" questions off ) to give me an opinion on whether there would be a solid mechanical or lore reason to not have a dex version.

If no real reason why not then should have something up and released this week once I have some spare time to throw the code together as it's pretty simple to just tweak the code I use for Carnage to do the same thing for Cournagon due to how it's set up to do it.

**Comment by Evilvonbek** [comment]
Yup, it passed the "don't see a reason why not since there's some monsters with similar" test so I'll hopefully get that rattled up and released before the weekend as long as real life doesn't get in the way.

**Comment by TKDancer** [comment]
yeah i assumed that creating a separate version would work best to avoid conflicts and what not, thanks for replying!
